env:
  mode: debug

server:
  port: 8080
  locale: "en"
  timezone: UTC

database:
  host: postgresql://neondb_owner:npg_Nns0WA4JGqgV@ep-jolly-block-a1v3g72a-pooler.ap-southeast-1.aws.neon.tech/wao?family=4

jwt:
  secret: 1234567890
  expires_at: 168h
