openapi: 3.0.3
info:
  title: Purchase Order API
  version: 1.0.0

paths:
  /purchase-order:
    post:
      summary: Create a new purchase order
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - items
              properties:
                items:
                  type: array
                  items:
                    type: object
                    required:
                      - product_id
                      - product_option_id
                      - quantity
                      - currency
                    properties:
                      product_id:
                        type: string
                        format: uuid
                      product_option_id:
                        type: string
                        format: uuid
                      quantity:
                        type: integer
                      currency:
                        type: string
      responses:
        '200':
          description: Purchase order created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    get:
      summary: Get list of purchase orders
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: A list of purchase orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseOrder'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /purchase-order/{id}:
    get:
      summary: Get details of a specific purchase order
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: Purchase order detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
        '404':
          description: Purchase order not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /purchase-order/{id}/status:
    patch:
      summary: Update the status of a purchase order
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Status updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Purchase order not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    PurchaseOrder:
      type: object
      required:
        - id
        - order_number
        - status
        - order_date
        - total_amount
        - currency
      properties:
        id:
          type: string
          format: uuid
        order_number:
          type: string
        status:
          type: string
        order_date:
          type: string
          format: date-time
        total_amount:
          type: number
          format: float
        currency:
          type: string
        timezone:
          type: string
        notes:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        created_by:
          type: string
          format: uuid
        updated_by:
          type: string
          format: uuid
        deleted_at:
          type: string
          format: date-time
          nullable: true
        items:
          type: array
          items:
            $ref: '#/components/schemas/PurchaseOrderItem'

    PurchaseOrderItem:
      type: object
      required:
        - id
        - purchase_order_id
        - product_id
        - product_option_id
        - product_name
        - product_option_name
        - unit_price
        - total_price
        - quantity
        - currency
      properties:
        id:
          type: string
          format: uuid
        purchase_order_id:
          type: string
          format: uuid
        product_id:
          type: string
          format: uuid
        product_option_id:
          type: string
          format: uuid
        product_name:
          type: string
        product_option_name:
          type: string
        unit_price:
          type: number
          format: float
        total_price:
          type: number
          format: float
        quantity:
          type: integer
        currency:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        created_by:
          type: string
          format: uuid
        updated_by:
          type: string
          format: uuid
        deleted_at:
          type: string
          format: date-time
          nullable: true