# yaml-language-server: ...
package: purchase_order
output: api/purchase_order/server.go
generate:
  gin-server: true
  models: true
  strict-server: true
  embedded-spec: true
output-options:
  # to make sure that all types are generated
  skip-prune: true