// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/LeHNam/wao-api/config"
	"github.com/LeHNam/wao-api/context"
	"github.com/LeHNam/wao-api/services/database"
	"github.com/LeHNam/wao-api/services/log"
	"github.com/LeHNam/wao-api/services/server"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.NewPostgresConnection(configConfig)
	if err != nil {
		return nil, err
	}
	logger := log.NewZapLogger(configConfig)
	serviceContext := context.NewServiceContext(configConfig, db, logger)
	serverServer := server.NewServer(serviceContext)
	return serverServer, nil
}
